### PR TITLE
Update/type refactor

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

**This contains breaking changes**

This implements the initial "logical types" design approved in PR #1571.  These changes amount to:

1. Improving `StandardTypes.hpp` to include the new platform type definitions
2. Improving `BasicTypes.hpp` to include _MIN and _MAX definitions
3. Reworking `FpConfig.hpp` to use `typedef`

This includes some "breaking changes".  

1. `StandardTypes.hpp` implementors **must** implement new types, or include `DefaultTypes.hpp` to get default implementations.  See `Fw/Types/Linux/StandardTypes.hpp` for an example
2. `BasicTypes.hpp` no longer includes the types defined in `FpConfig.hpp`.  Users should switch to include `FpConfig.hpp` when needing project-defined types
3. `AssertArg` has been renamed `FwAssertArgType`.  Users must update.

This PR also includes some deprecated features:

1. Use of `NATIVE_INT_TYPE`, `NATIVE_UINT_TYPE` and `POINTER_CAST` is no longer advised.  Projects should update, at minumum, to use `PlatformIntType`, `PlatformUIntType` and `PlatformPointerCastType` respectively.
2. Use of `PlatformIntType`, `PlatformUIntType` is discouraged outside of API calls returning `int` and `unsigned int` respectively. Other uses should be replaced with new "logical types".  e.g. `NATIVE_INT_TYPE` in port calls should be replaced with `FwIndexType`.

Other restrictions:
1. `DefaultTypes.hpp` should only ever be included in a `StandardTypes.hpp` header.  All other users should be using `FpConfig.hpp` and trusting it to setup the types correctly.

## Future Work

Define new "logical types" when identified.
Replace uses of PRI[xud]NN for "logical types" with defined equivalent.

### CODE REVIEW

**Comment by LeStarch** [comment]
Do autocoders need to switch to FpConfig.hpp

**Comment by LeStarch** [comment]
look-up int pointer t

**Comment by LeStarch** [comment]
Rename StandardTypes.hpp -> PlatformTypes.hpp

**Review by kevin-f-ortega — COMMENTED** [review]
Thank you Michael. These changes look great! I have some minor comments:

You have duplicate `#include <FpConfig.hpp>` lines in these files

Autocoders/Python/bin/tlm_packet_gen.py
Autocoders/Python/src/fprime_ac/generators/templates/port/includes1PortH.tmpl
Fw/Cfg/ConfigCheck.cpp
Fw/Cmd/CmdArgBuffer.hpp
Fw/Cmd/CmdString.hpp
Fw/Com/ComBuffer.hpp
Fw/Log/LogBuffer.hpp
Fw/Log/LogString.hpp
Fw/Log/TextLogString.hpp
Fw/Obj/ObjBase.hpp
Fw/Obj/SimpleObjRegistry.hpp
Fw/Port/InputPortBase.cpp
Fw/Port/InputPortBase.hpp
Fw/Port/OutputPortBase.cpp
Fw/Port/OutputPortBase.hpp
Fw/Prm/PrmBuffer.hpp
Fw/Prm/PrmString.hpp
Fw/Time/Time.hpp
Fw/Tlm/TlmBuffer.hpp
Fw/Tlm/TlmString.hpp
Fw/Trap/TrapHandler.hpp
Fw/Types/Assert.hpp
Fw/Types/CAssert.hpp
Fw/Types/InternalInterfaceString.hpp
Fw/Types/PolyType.hpp
Os/Baremetal/File.cpp
Os/Baremetal/FileSystem.cpp
Os/Directory.hpp
Os/FileCommon.cpp
Os/File.hpp
Os/FileSystem.hpp
Os/Linux/Directory.cpp
Os/Linux/File.cpp
Os/Linux/FileSystem.cpp
Os/QueueString.hpp
Os/Stubs/Linux/FileStub.cpp
Os/Task.hpp
Os/TaskString.hpp
Utils/Types/CircularBuffer.hpp

**Comment by kevin-f-ortega** [comment]
Also, the Python Autocoder files still use AssertArg e.g. `Autocoders/Python/src/fprime_ac/generators/templates/component/cpp.py` ? I suspect those files are no longer maintained.

**Review by kevin-f-ortega — APPROVED** [review]
LGTM. I was able to build it on my side. Thank you!

**Comment by kevin-f-ortega** [comment]
I tried this one out and it compiled with my system. But is https://github.com/nasa/fprime/pull/1615 a duplicate of this PR?

**Review by kevin-f-ortega — APPROVED** [review]

**Pull request closed without merging**
