### PR TITLE
astroesteban: fix incorrect component naming in test template

### PR DESCRIPTION
**Pull request by astroesteban**
| | |
|:---|:---|
|**_Originating Project/Creator_**|@astroesteban |
|**_Affected Component_**|  Test Header Template|
|**_Affected Architectures(s)_**|Test Stubs Autogen  |
|**_Related Issue(s)_**| None |
|**_Has Unit Tests (y/n)_**| N |
|**_Builds Without Errors (y/n)_**| Y |
|**_Unit Tests Pass (y/n)_**| Y |
|**_Documentation Included (y/n)_**| N |

---
## Change Description

Updates the source code template cpp.tmpl to have the header include:
```
\#include "${include_path}/${name}ComponentImpl.hpp"
```

Renames the component name references in the hpp.tmpl  from `${name}ComponentImpl` to just `${name}`.

## Rationale

I purged all of my existing autogenerated files and started from scratch with the FPP templates. Here is what I found:

1. The autogenerated component sources append `ComponentImpl` to the file name. So if I have a Blinker.fpp file with a Blinker component in it I end up with `BlinkerComponentImpl.hpp` and `BlinkerComponentImpl.cpp`
2. In the `BlinkerComponentImpl.cpp` the include macro for the corresponding header is just `Blinker.hpp` instead of `BlinkerComponentImpl.hpp`.
3. In the test stubs the type of the component is `BlinkerComponentImpl` instead of just `Blinker`.

The most recent changes to this pull request fix all of the above issues so I am able to run the following commands without any interventions or errors:
```
fprime-util generate
fprime-util impl
fprime-util build

fprime-util generate --ut
fprime-util impl --ut
fprime-util build --ut
```

## Testing/Review Recommendations

- Test against Ref.

## Future Work

None.

### CODE REVIEW

**Comment by astroesteban** [comment]
I purged all of the autogenerated files from my repo and recreated everything starting from the FPP files.

It looks like the generated component sources are indeed `BlinkerComponentImpl.hpp` but the type of the component included in the Tester files is still `BlinkerComponentImpl component`. So it looks like that change is still required but I need to undo the renaming of the header file.

**Comment by LeStarch** [comment]
Wow, this one was on my short list to fix, and you got it done.  Thank you.

**Comment by astroesteban** [comment]
Happy to help!

**Review by kevin-f-ortega — APPROVED** [review]
Thank you!

**Comment by LeStarch** [comment]
@astroesteban instead of renaming the include, I renamed the file instead.  FPP has the feature that it can detect headers when they follow the naming convention `<component>.hpp` so we are moving toward those names for files.  This fixes that, but keeps your other fix.

**Comment by LeStarch** [comment]
@astroesteban I ended up fixing the `TestMain.cpp` generation too.  Thanks for letting me work within your PR.

**Comment by astroesteban** [comment]
@LeStarch No problem at all. I'm just happy to help improve FPrime 👍🏼

**Comment by LeStarch** [comment]
Somehow I botched this PR.  Let me fix it if I  can

**Comment by LeStarch** [comment]
See #1520

**Pull request closed without merging**
