### PR TITLE
Add RTEMS5 support

### PR DESCRIPTION
**Pull request by matzipan**
The RTEMS platform file definition can be further discussed. Its current implementation is something that is tied to our internal build system.

I'm not sure why `netinet/in.h` needed to be included explicitly in `SocketIpDriverComponentImpl.hpp`.

For direct sync, I found some POSIX tailoring documentation for RTEMS 4 which said `O_DSYNC` is not implemented, but I couldn't find documentation to reflect that for RTEMS 5 as well.

I'm unsure whether `TaskDelay` is a good choice for `Svc/LinuxTimer`.

This PR doesn't add any support for RTEMS5 in the current build system. It only touches the CMake build system.

### CODE REVIEW

**Comment by LeStarch** [comment]
This looks ok to me...but I don't see the implementation for Svc/LinuxTimer.

**Comment by timcanham** [comment]
The intent is not for every port to do their own version of LinuxTimer. It really is meant for Linux only. I provided a `TaskDelay` alternative for Linux systems that did not have the `timer_fd`. The `TaskDelay` is not the purest approach, since it will walk every cycle due to execution times between calls. The `timer_fd` will keep a consistent interval. For an embedded system, the developer would write a timer driver based on their own hardware such as hardware timers.

**Comment by timcanham** [comment]
Is there a more generic RTEMS timer mechanism that could be used?

**Comment by timcanham** [comment]
If `nanosleep` is in the RTEMS kernel, then the `taskDelay` method would work as a demonstrator, but I would not use it as a baseline.

**Comment by matzipan** [comment]
Hi guys. Apologies for the long delay in my response:

RTEMS provides two different APIs, one is the so-called "classic" API. The other is the POSIX API.

The layer in this PR uses the POSIX API, which is why I could re-use the LinuxTimer. I guess this warrants perhaps a rename of LinuxTimer to PosixTimer?

> Is there a more generic RTEMS timer mechanism that could be used?

The layer could be brought down to use the classic API timers, but I'm not sure if having such a mixture of API layers is a good idea.

> Also, has this been tested? If so, can you elaborate?

I just checked what I wrote in my internal JIRA ticket, and it appears I managed to get it to run on our boards on top of RTEMS. There seems to be some issue at the end, but it wasn't in the scope of the work at the time to look into it further. Below is the log: 
```
DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0051 registered to port 6 slot 0
EVENT: (121) (2:567993600,85313) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0052 registered to port 6 slot 1
EVENT: (121) (2:567993600,95856) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0053 registered to port 6 slot 2
EVENT: (121) (2:567993600,106403) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0054 registered to port 6 slot 3
EVENT: (121) (2:567993600,117038) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x005B registered to port 6 slot 4
EVENT: (121) (2:567993600,127672) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x005C registered to port 6 slot 5
EVENT: (121) (2:567993600,138306) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x005D registered to port 6 slot 6
EVENT: (121) (2:567993600,148973) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x005E registered to port 6 slot 7
EVENT: (121) (2:567993600,159612) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0065 registered to port 7 slot 8
EVENT: (121) (2:567993600,170252) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0066 registered to port 7 slot 9
EVENT: (121) (2:567993600,180895) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0067 registered to port 7 slot 10
EVENT: (121) (2:567993600,191642) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0068 registered to port 7 slot 11
EVENT: (121) (2:567993600,202389) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x021D registered to port 4 slot 12
EVENT: (121) (2:567993600,213135) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x021E registered to port 4 slot 13
EVENT: (121) (2:567993600,223882) DIAGNOSTISP) OpCodeRegistered : Opcode 0x0220 registered to port 4 slot 15
EVENT: (121) (2:567993600,245376) DIAGNOSTIC: (CMDDISP) OpCoded : Opcode 0x0222 registered to port 4 slot 17
EVENT: (121) (2:567993600,266879) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opco registered to port 1 slot 19
EVENT: (121) (2:567993600,288390) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x007A registert 1 slot 21
EVENT: (121) (2:567993600,309902) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x007C registered to port 1 slot : (121) (2:567993600,331427) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x01A6 registered to port 0 slot 24
EVENT: (121) (00,352950) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x01A8 registered to port 0 slot 26
EVENT: (121) (2:567993600,363715TIC: (CMDDISP) OpCodeRegistered : Opcode 0x008D registered to port 3 slot 28
EVENT: (121) (2:567993600,385253) DIAGNOSTIC: (CMDodeRegistered : Opcode 0x01F6 registered to port 5 slot 30
EVENT: (121) (2:567993600,406792) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x00B5 registered to port 8 slot 31
EVENT: (121) (2:567993600,417562) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x00B6 registered to port 8 slot 32
EVENT: (121) (2:567993600,428335) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x00B7 registered to port 8 slot 33
EVENT: (121) (2:567993600,439114) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x00DD registered to port 9 slot 34
EVENT: (121) (2:567993600,449881) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x00DE registered to port 9 slot 35
EVENT: (121) (2:567993600,460654) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x00DF registered to port 9 sloENT: (121) (2:567993600,482315) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x00CA registered to port 10 slot 38
EVENT: (127993600,504081) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0141 registered to port 11 slot 40
EVENT: (121) (2:567993600,DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0143 registered to port 11 slot 42
EVENT: (121) (2:567993600,536727) DIAGNOSTDISP) OpCodeRegistered : Opcode 0x011A registered to port 12 slot 44
EVENT: (121) (2:567993600,558499) DIAGNOSTIC: (CMDDISP) Opstered : Opcode 0x0169 registered to port 2 slot 46
EVENT: (121) (2:567993600,580207) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : 016B registered to port 2 slot 48
EVENT: (121) (2:567993600,601781) DIAGNOSTIC: (CMDDISP) OpCodeRegistered : Opcode 0x0029 registage 0 with record 0 and error 1
EVENT: (141) (2:567993600,625051) WARNING_LO: (PRM) PrmIdNotFound : Parameter ID 0x00000065 not found
EVENT: (141) (2:567993600,634426) WARNING_LO: (PRM) PrmIdNotFound : Parameter ID 0x00000066 not found
EVENT: (141) (2G_LO: (PRM) PrmIdNotFound : Parameter ID 0x00000052 not found
Assert file "/home/andrei/Workspace/on-board-software/vendor/fpriExiting.
```

Please let me know what changes you would like me to do to this PR to get it merged.

**Comment by timcanham** [comment]
@matzipan: Does the RTEMS POSIX layer support the `LinuxTimerComponentImplTimerFd.cpp` implementation? That would be nice, but it's only supported on more recent versions of Linux.

The `TaskDelay()` approach would work for now, and we can do the PR, but I was hoping there was something in the RTEMS API we could use to get a true timer.

**Comment by timcanham** [comment]
@matzipan Would you be willing to share the procedure you used to compile F prime with RTEMS?

**Comment by matzipan** [comment]
> Would you be willing to share the procedure you used to compile F prime with RTEMS?

Unfortunately our build system customizes the RTEMS build system in that it builds it entirely in CMake, without the autoconf or the newer WAF build system. We then link both fprime and rtems as libraries in a final executable. I can't say how this would look using the regular RTEMS build system, but I guess you could still statically link it in there.

So ultimately we change `fprime/Ref/Top/CMakeLists.txt` and append to it the following content: 

```
target_compile_options(fprime-demo
  PRIVATE
  ${RTEMS_C_FLAGS}
)

target_link_options(fprime-demo
  PRIVATE
  ${RTEMS_LINK_FLAGS}
)

target_include_directories(fprime-demo PRIVATE
  ${RTEMS_INCLUDE_DIRS}
  ${RTEMS_BSP_INCLUDE_DIRS}
  ${RTEMS_SOURCE_DIR}/testsuites/support/include
)

target_link_libraries(fprime-demo rtemscpu rtemstest rtemsbsp)
target_include_directories(fprime-demo PRIVATE ${FPRIME_CURRENT_BUILD_ROOT})

target_compile_definitions(fprime-demo
  PRIVATE
  __rtems__
  _POSIX_THREADS
)

add_dependencies(fprime-demo bsps-start)

post_processing(fprime-demo)
```

`bsp-start` is the startup assembly script from the BSP.

`fprime/Ref/Top/Main.cpp` is changed to:

```
extern "C" {
#define CONFIGURE_INIT

#include "system.h"
}

#include <examples/fprime-demo/Top/Components.hpp>


rtems_task Init(rtems_task_argument argument) {
  U32 port_number = 50000;
  char *hostname= const_cast<char *>("0.0.0.0");
  bool dump = false;

  printf("Hello world!\n");

  bool quit = constructApp(dump, port_number, hostname);
  if (quit) {
    printf("Unable to construct app. Quitting.\n");
  }
}
```

`system.h` is a typical RTEMS configuration definitions file:
```
#include <rtems.h>

// Functions

rtems_task Init(rtems_task_argument argument);

// For device driver prototypes
#include <bsp.h>

// RTEMS configuration information

#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER

#define CONFIGURE_MAXIMUM_TASKS 4

#define CONFIGURE_MAXIMUM_SEMAPHORES 1

#define CONFIGURE_MINIMUM_TASK_STACK_SIZE 4096

#define CONFIGURE_RTEMS_INIT_TASKS_TABLE

#define CONFIGURE_EXTRA_TASK_STACKS (3 * RTEMS_MINIMUM_STACK_SIZE)

#define CONFIGURE_UNIFIED_WORK_AREAS
#define CONFIGURE_LIBIO_MAXIMUM_FILE_DESCRIPTORS 5

#define CONFIGURE_INTERRUPT_STACK_SIZE 4096

#include <rtems/confdefs.h>
```

**Comment by matzipan** [comment]
> Would you be willing to share the procedure you used to compile F prime with RTEMS?

Unfortunately our build system customizes the RTEMS build system in that it builds it entirely in CMake, without the autoconf or the newer WAF build system. We then link both fprime and rtems as libraries in a final executable. I can't say how this would look using the regular RTEMS build system, but I guess you could still statically link it in there.

So ultimately we change `fprime/Ref/Top/CMakeLists.txt` and append to it the following content: 

```
target_compile_options(fprime-demo
  PRIVATE
  ${RTEMS_C_FLAGS}
)

target_link_options(fprime-demo
  PRIVATE
  ${RTEMS_LINK_FLAGS}
)

target_include_directories(fprime-demo PRIVATE
  ${RTEMS_INCLUDE_DIRS}
  ${RTEMS_BSP_INCLUDE_DIRS}
  ${RTEMS_SOURCE_DIR}/testsuites/support/include
)

target_link_libraries(fprime-demo rtemscpu rtemstest rtemsbsp)
target_include_directories(fprime-demo PRIVATE ${FPRIME_CURRENT_BUILD_ROOT})

target_compile_definitions(fprime-demo
  PRIVATE
  __rtems__
  _POSIX_THREADS
)

add_dependencies(fprime-demo bsps-start)

post_processing(fprime-demo)
```

`bsp-start` is the startup assembly script from the BSP.

`fprime/Ref/Top/Main.cpp` is changed to:

```
extern "C" {
#define CONFIGURE_INIT

#include "system.h"
}

#include <examples/fprime-demo/Top/Components.hpp>


rtems_task Init(rtems_task_argument argument) {
  U32 port_number = 50000;
  char *hostname= const_cast<char *>("0.0.0.0");
  bool dump = false;

  printf("Hello world!\n");

  bool quit = constructApp(dump, port_number, hostname);
  if (quit) {
    printf("Unable to construct app. Quitting.\n");
  }
}
```

`system.h` is a typical RTEMS configuration definitions file:
```
#include <rtems.h>

// Functions

rtems_task Init(rtems_task_argument argument);

// For device driver prototypes
#include <bsp.h>

// RTEMS configuration information

#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER

#define CONFIGURE_MAXIMUM_TASKS 4

#define CONFIGURE_MAXIMUM_SEMAPHORES 1

#define CONFIGURE_MINIMUM_TASK_STACK_SIZE 4096

#define CONFIGURE_RTEMS_INIT_TASKS_TABLE

#define CONFIGURE_EXTRA_TASK_STACKS (3 * RTEMS_MINIMUM_STACK_SIZE)

#define CONFIGURE_UNIFIED_WORK_AREAS
#define CONFIGURE_LIBIO_MAXIMUM_FILE_DESCRIPTORS 5

#define CONFIGURE_INTERRUPT_STACK_SIZE 4096

#include <rtems/confdefs.h>
```

**Comment by matzipan** [comment]
> Does the RTEMS POSIX layer support the LinuxTimerComponentImplTimerFd.cpp implementation? 

I wasn't familiar with timerfd. I see this is a linux syscall. Looking for `timerfd` through RTEMS source reveals nothing.

> but I was hoping there was something in the RTEMS API we could use to get a true timer.

What do you mean by `true timer`? There's such a thing such as a [Timer Manager](https://docs.rtems.org/branches/master/c-user/timer_manager.html) in the classic API. Which is also exposed through [these](https://docs.rtems.org/releases/rtems-docs-4.11.2/posix-users/timer.html) POSIX API calls

[This](https://docs.rtems.org/releases/rtems-docs-4.11.2/posix-users/status_of_implementation.html) is a reference of POSIX API tailoring for RTEMS.

**Comment by matzipan** [comment]
Forgot to mention also the [Rate Monotonic Manager](https://docs.rtems.org/branches/master/c-user/rate_monotonic_manager.html) API.

**Comment by timcanham** [comment]
It looks like the `rtems_status_code rtems_timer_fire_after` call is what we would want. It fires periodically and we provide a callback to drive the rate group.

**Comment by matzipan** [comment]
In this case, I think you might like thE rate monotonic one. Since the normal API is susceptible to drift.

Shall we merge the first version With the timedelay and then leave an open issue for implementing the other one?

**Pull request merged**
