### PR TITLE
Using TAB escape sequence instead of pure spaces

### PR DESCRIPTION
**Pull request by lnxpy**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

- Using the escape sequences instead of spaces.
- Using [isort](https://isort.readthedocs.io/en/latest/) in order to sort imports in the entire project.

## Rationale

In some cases, like when you want to stream the STDOUT and you are about the stream a huge amount of data like log records, using the pure spaces might break the responsiveness in the CLI. Better approach is to use sequences. In spite, I found some escape sequences like `\n` in the code, but there were pure spaces (4 spaces) instead of `\t`. It also helps for better readability.

## Testing/Review Recommendations

Please make sure you run a full test. Despite of isort's power, there still might be some special cases that isort may cause of import errors and stuff. However, I've never faced any of them.

### CODE REVIEW

**Review by LeStarch — APPROVED** [review]
Looks good to me.  My guess is the python formatter is going to break on the changes where lines have collapsed.... but this is for CI to catch.

In the future, I'd suggest splitting such PRs into two, as the original (tabs) was easy to review, but the larger one at 62 files took much longer to review.

Regardless, thanks for the PR.  We'll see how CI does.

**Comment by lnxpy** [comment]
Thank you. I actually started using escape sequences in only one file from the project to begin this methodology of logging or even printing stuff to the CLI in a better scheme and shape. Almost all those 61 files are being modified because I tried to sort the import lists of the entire project and I highly believe that CI failure must be due to second commit.

**Comment by LeStarch** [comment]
Closing and reopening as that seems to force a full rerun of the failing CI.

**Comment by LeStarch** [comment]
@lnxpy it might be, but we've had a failing CI for a week that was resolved only today.  Thus I am rerunning all things before I take the failures seriously.

**Comment by LeStarch** [comment]
@Inxpy yes, now the formatter is balking because the tool you ran changed the format.  To fix, I recommend you run:

```
pip install click==8.0.4 black==21.6b0
cd fprime
black .
```

That should clean up the files and fix the issue!  It will still keep the sorted imports, but will correct the collapsed lines.  Let me know if you need help running this!

**Comment by lnxpy** [comment]
@LeStarch Would you please close and reopen for another CI rerun?

**Review by LeStarch — APPROVED** [review]

**Comment by LeStarch** [comment]
This is great work.  Thanks for getting this prepared!

**Pull request merged**
