### PR TITLE
Refactoring `format_type_item` function of `JSONDictionaryGen.py`

### PR DESCRIPTION
**Pull request by ThibFrgsGmz**
| | |
|:---|:---|
|**_Originating Project/Creator_**| @ThibFrgsGmz |
|**_Affected Component_**| python autocoder |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**| void |
|**_Has Unit Tests (y/n)_**| n |
|**_Builds Without Errors (y/n)_**| Let CI run |
|**_Unit Tests Pass (y/n)_**| Let CI run |
|**_Documentation Included (y/n)_**| n |

---
## Change Description

This PR aims to refactor the `format_type_item` function of `JSONDictionaryGen.py`.
 
## Rationale

- Swap the `if /else` statements to stop reading the function as soon as possible
- Remove the unnecessary `else` statement to limit nested statements
- list comprehension to run faster than building the collection in a loop and in one line.

## Testing/Review Recommendations

void

## Future Work

 void

### CODE REVIEW

**Review by LeStarch — APPROVED** [review]

**Comment by LeStarch** [comment]
@ThibFrgsGmz see: #1533 .  We are removing a bunch of dead code.  This file is one of them, so I am going to close this.

**Comment by ThibFrgsGmz** [comment]
@LeStarch Ok, so much the better because I had seen a lot of things to refactor and unless I'm mistaken, a lot of the files were the same as in fprime-util, right?

**Comment by ThibFrgsGmz** [comment]
Will there be another pass to purge dead/depreciated code? That I reduce the technical debt of the code base that is actually useful.

**Comment by LeStarch** [comment]
@Joshua-Anderson is right, I don't have any specific intentions to delete more....but we are migrating away from the Autocoders package and to FPP.  The current autocoder is an "under-the-hood" thing right now.

**Comment by ThibFrgsGmz** [comment]
Ok so there is no point in spending time on the python code of the main repo?

Do you have a deadline to switch everything to FPP? I don't see any info on GitHub, so I'm a bit caught off guard! 

In python code there will be only fprime-util and fprime-gds perennial?

I will have to learn Scala to collaborate on FPP ^^"

**Comment by LeStarch** [comment]
Yes, `fprime-tools` and `fprime-gds` are perennial.  They are long term projects and although is not indicated by the speed at which I can review PRs, I appreciate all the python work you've been doing.

We are in a phase of development for FPP where we are doing model processing in FPP and then passing a generated XML model to the python Autocoders. That means there is limited Python work that must still be done

1.  Bug fixes
2. Feature requests

I expect we'll remain in this phase for some time, and thus I am trying to review your refactors carefully because they improve the effectiveness of both items 1 and 2 above. So yes, this code is slated for removal, but cannot be abandoned yet.

I did realize once your last batch of PRs came in that you were refactoring through code that was entirely dead.  I apologize for not removing those files sooner as it would have saved you the effort.

**Comment by ThibFrgsGmz** [comment]
OK, I will continue on `fprime-tools` and `fprime-gds`.

For `fprime`, I will continue anyway now that the dead code is gone.
This trains me and shows potential contributors that the open source project is very active.

Is that okay with you? (I have identified more than 10-20 PRs to do).

I don't think I'll be able to contribute to `fpp` for a long time: until I know the Scala language and the associated linters.

**Pull request closed without merging**
