### PR TITLE
Fix uninformative exception in TopoFactory.py

### PR DESCRIPTION
**Pull request by aaronbuchwald**
Fix blank exception thrown while reading Topology file

### CODE REVIEW

**Comment by aaronbuchwald** [comment]
Also this exception is being thrown after changing all of the base ids, so that there is no longer a conflict. Would it be possible to change this, so that when all of the base ids in the current version of the topology file do not overlap there is no exception thrown at all?

**Comment by LeStarch** [comment]
Great!  Let me take a look.

**Comment by LeStarch** [comment]
Looks good to me.  I see a better message in the Exception when violated.  Thank you!

**Comment by LeStarch** [comment]
I switched the input branch to `devel`

**Pull request merged**
