### PR TITLE
lestarch: rewriten Fw::Buffer SDD. Fixes #1283

### LINKED ISSUE #1283: SDD for Fw::Buffer is out of date
The SDD [here](https://github.com/nasa/fprime/blob/devel/Fw/Buffer/docs/sdd.md) describes the original design of `Fw::Buffer`. The implementation has changed under the design.

The updated design doc should specify what is a valid or invalid buffer in the current design.

* The old design said that an invalid buffer has address zero.
* The address is now a pointer, not an integer, so it should probably change to something like "an invalid buffer has size zero."

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Updated the `Fw::Buffer` SDD to match newer implementation. Fixes #1283.

### CODE REVIEW

**Review by bocchino — COMMENTED** [review]
Looks good, just a few comments.

**Comment by LeStarch** [comment]
@bocchino I reworded that sentence to describe member status and constructor function.  I agree that the alternative implementation makes a lot of sense, but it is outside the scope of this PR.

**Comment by LeStarch** [comment]
Closed and reopened as I needed to try and re-trigger a complete rerun of CI to fix the python formatting bug. If it doesn't work, we'll ignore that check as the python was not touched.

**Review by bocchino — APPROVED** [review]
Looks good!

**Pull request merged**
