### PR TITLE
lestarch: adding in a blank settings.ini to Ref

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Add in `settings.ini` to `Ref`.  Leaves same behavior as `Ref` but removes the WARNING.

### CODE REVIEW

**Comment by LeStarch** [comment]
@ThibFrgsGmz figured it was easier to do than write as an issue to resolve.....

**Comment by ThibFrgsGmz** [comment]
@LeStarch No problem. I'm used to almost always creating an issue before doing a PR (some QA people require us to do this absolutely) but for small fixes it's easier to directly do a PR with a description.

We should add comments where we redirect to the associated documentation or the RPI for example. We can also paraphrase your comment from issue #1207 .

We could also reference the "future" ``awesome-fprime`` project, which we were talking about a few months ago, to refer the user to various concrete implementation cases. They will see how others handle the ``settings.ini`` of F Prime.

**Comment by LeStarch** [comment]
@ThibFrgsGmz good point, I should add comments pointing to the docs!

**Comment by LeStarch** [comment]
@ThibFrgsGmz done!

**Review by ThibFrgsGmz — APPROVED** [review]

**Comment by LeStarch** [comment]
Fixed issues, received review from requestor.

**Pull request merged**
