### PR TITLE
Update fpp-locs-deps to work cleanly with the latest FPP tools

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Patching fpp-locs while we improve the build.

### CODE REVIEW

**Comment by LeStarch** [comment]
@bocchino I broke out this bug fix from the larger performance work.  You reviewed this a few weeks ago, and we were waiting for CI to pass.  It now passes here.

**Review by bocchino — COMMENTED** [review]
Looks good! Can we get the latest from fpp/main into here? That way CI can check it. Looks like main is a few commits of the commit you have here.

**Comment by LeStarch** [comment]
@bocchino done!

**Review by bocchino — APPROVED** [review]
Looks good!

**Pull request merged**
