### PR TITLE
lestarch: adding in fprime-util new

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Originating Project/Creator_**| Infrastructure |
|**_Affected Component_**| fprime-util |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**| n |
|**_Builds Without Errors (y/n)_**| n  |
|**_Unit Tests Pass (y/n)_**| n  |
|**_Documentation Included (y/n)_**| y -- CLI |

---
## Change Description

Adds in a `fprime-util new` command to create new components.  Thanks to Georgia Tech's cookiecutter.

## Rationale

Simplifies the process of making components.

## Future Work

1. Add in Port and Topology cookiecutters
2. Allow specifying project-supplied cookiecutter package
3. Clean-up versioning of cookiecutters

### CODE REVIEW

**Comment by LeStarch** [comment]
For safety, when possible I like to avoid deleting files. Is it possible to send a PR to remove the makefiles from the cookiecutter template instead?

**Comment by LeStarch** [comment]
Just deleting the first 11 lines of the file feels really brittle and dangerous, what if the cookiecutter template is updated? Is there a smarter way we can merge the files?

**Comment by LeStarch** [comment]
I don't think we want to have fprime using the latest version of the cookiecutter template. What if the template is updated for the latest version of F', but the user is using an older version of fprime?

What I would do is version the cookiecutter template with fprime, and have fprime-util pull the template version corresponding to the users fprime version.

I'd also prefer to ship the cookiecutter template as part of the fprime-util package (to install it when you pip install fprime-util), since it's nice not to pull in internet dependencies when possible, but this might conflict with however the cookiecutter template is versioned and will require more thought.

**Comment by LeStarch** [comment]
Comments pulled from #357 context available there.

**Comment by LeStarch** [comment]
Decisions: add a "prototype" warning, and ship as a prototype feature.  We can add the ability to change cookiecutter templates later.

**Review by Joshua-Anderson — APPROVED** [review]
Since CI no longer unit tests fprime-util, approval is contingent on fprime-util unit tests passing locally.

**Comment by LeStarch** [comment]
Confirming local UT run passes.

**Pull request merged**
