### PR TITLE
changed minimum version to 3.18

### PR DESCRIPTION
**Pull request by rithvikrajraapeti**
| | |
|:---|:---|
|**_Related Issue(s)_**|  changing the cmake minimum version to be 3.18|
|**_Has Unit Tests (y/n)_**|  n|
|**_Documentation Included (y/n)_**| n |

---
## Change Description
changed the minimum version to 3.18 

## Future Work

Note any additional work that will be done relating to this issue.

### CODE REVIEW

**Comment by LeStarch** [comment]
@rithvikrajraapeti what specifically caused the need for this change?  Is CMake 3.16 causing issues here?

**Comment by rithvikrajraapeti** [comment]
For me it didnt run properly

**Comment by rithvikrajraapeti** [comment]
And even the version is outdated and it may cause some issues

**Comment by rithvikrajraapeti** [comment]
And its only considring the .cpp files and not the .h files if i added it

**Comment by rithvikrajraapeti** [comment]
Only for me

**Comment by rithvikrajraapeti** [comment]
And i saw this issue and this is common and you can change the version to 1.18

**Comment by rithvikrajraapeti** [comment]
and what happend to a test

**Comment by LeStarch** [comment]
We haven't seen this failure in our side.  To fix this in a project, it is best to add that statement to the top of your project `CMakeLists.txt`.

If there is still an issue, please post the error you received and we can help debug.  For now we are hesitant to up the minimum version for all users until we see a concrete error with it.

**Pull request closed without merging**
