### PR TITLE
fix(docs): corrects common typos in project documentation

### PR DESCRIPTION
**Pull request by plan-do-break-fix**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**| docs |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  n|
|**_Builds Without Errors (y/n)_**| y |
|**_Unit Tests Pass (y/n)_**| y |
|**_Documentation Included (y/n)_**| y |

---
## Change Description

A description of the changes contained in the PR.
Scope of changes is restricted to HTML docs. Changes made in agreement with Standard American English.
## Rationale

A rationale for this change. e.g. fixes bug, or most projects need XYZ feature.

## Testing/Review Recommendations

Fill in testing procedures, specific items to focus on for review, or other info to help the team verify these changes are flight-quality.

## Future Work

Note any additional work that will be done relating to this issue.

### CODE REVIEW

**Comment by jsoref** [comment]
@LeStarch: it feels like this documentation is an attractive nuisance 🙁 .

@plan-do-break-fix: fwiw the underlying content was already fixed:
https://github.com/nasa/fprime/search?q=%22address+space.+This+means+that+it+never+touches+the+filesystem+and%22

it's just waiting for a release when the /doc/ content gets regenerated.

**Comment by LeStarch** [comment]
@jsoref yes it is.  As you said, we have fixed the underlying content....so changes to the raw HTML are unnecessary.

**Comment by LeStarch** [comment]
After thinking about it a bit, we are going to pull these auto-generated files out into a separate area, as their constant mismatch with the source files isn't great.

Moving forward we can look at more efficient ways to handle/host this content....but making this adjustment will remove the confusion.

**Comment by LeStarch** [comment]
Closing as it edits auto generated files.

**Pull request closed without merging**
