### PR TITLE
Fill in the `projects.md` file

### PR DESCRIPTION
**Pull request by ThibFrgsGmz**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**| N/A |
|**_Affected Architectures(s)_**| N/A |
|**_Related Issue(s)_**| N/A |
|**_Has Unit Tests (y/n)_**| N/A |
|**_Builds Without Errors (y/n)_**| N/A |
|**_Unit Tests Pass (y/n)_**| N/A |
|**_Documentation Included (y/n)_**| y |

---
## Change Description

This PR is intended to supplement the `projects.md` file with publicly available information.

## Rationale

This file should have been completed some time ago.

## Testing/Review Recommendations

Fill in the information I couldn't find.

## Future Work

N/A

### CODE REVIEW

**Comment by LeStarch** [comment]
Where did this information come from?

**Comment by ThibFrgsGmz** [comment]
Which one in particular? My sources of information are publicly available and come mainly from the [JPL technical report server](https://trs.jpl.nasa.gov/). 

In 2022-03-05, @timcanham published the following report: ["The Mars Ingenuity Helicopter - A Victory for Open-Source Software"](https://trs.jpl.nasa.gov/handle/2014/55998); apparently presented at the "2022 IEEE Aerospace Conference, Big Sky, Montana, March 5-12, 2022".
It shows that the following projects have used FPrime: RapidScat, Asteria, Lunar FlashLight, NEA Scout, OWNLS and Ingenuity.

As for CADRE and COLDARM, they are mentioned next to the above projects in the 2021-07-26 presentation of ["F Prime Product Line Overview"](https://trs.jpl.nasa.gov/handle/2014/55586), apparently presented by Jeff Levison, @timcanham  and yourself (@LeStarch) at the "VIRTUAL IEEE International Conference on Space Mission Challenges for Information Technology (SMC-IT 2021), New York, New York, July 26-30, 2021".

NOTE: regarding the format of the table, I have taken the one I proposed last year in the discussion: https://github.com/nasa/fprime/discussions/844#discussioncomment-1034434

**Comment by LeStarch** [comment]
@ThibFrgsGmz cool!  I just wanted to confirm it comes through publicly available sources! I am trying to find someone who can review this work at a higher level.  Personally I like it, although I might replace the `?`s with just empty cells.

I'd also remove the class column until we have some published works that reference that.

Here is some additional info:

LunarFlashlight and Neascout run VxWorks (Os) on Platform (Sphinx)

(https://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=5263&context=smallsat)

Asteria is running Linux on a PowerPC on the CORTEX 160:

"ASTERIA uses the CORTEX 160 flight computer from
Spaceflight Industries for onboard processing and
command and data handling. It uses a Virtex 4FX FPGA
with an embedded PowerPC processor running Linux.
JPL modified the firmware to incorporate a custom
interface with the imager driver board and to add SPI
interfaces that are used to interact with subsystem
components."

https://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=4067&context=smallsat

**Comment by ThibFrgsGmz** [comment]
@LeStarch I have changed the format to suit you and I have revised the way I have placed the hyperlinks.

I have put the two publications you gave me as references. I had never read the ASTERIA one, it seems to me that it is very interesting!

I'm a bit afraid that the "HW Platform" column is not well enough done and ends up being a catch-all (platform, CPU, architecture, RAM, etc...).
Maybe we should split it into two or three columns? `HW Platform` / `CPU` / `Architecture`?

**Review by LeStarch — APPROVED** [review]

**Comment by LeStarch** [comment]
I got verbal approval and this looks good!

**Comment by LeStarch** [comment]
Platform seems ok for now.  I am going to merge as this is a definite improvement over "coming soon".

**Pull request merged**
