### PR TITLE
Fix/deframer ut

### LINKED ISSUE #1366: Seeding STest::Random causes a failure in Deframer unit tests
Steps to reproduce:

1. In `Svc/Deframer/test/ut-unified/TestMain.cpp`, add the line `STest::Random::seed();` just before `return RUN_ALL_TESTS();`
2. In `Svc/Deframer`, run `fprime-util build --ut`
3. In `build-fprime-automatic-native-ut/bin/[native os name]`
    1. Run `echo 545994 > seed`. This step captures the random seed that causes the issue to appear.
    2. Run `./Svc_Deframer_with_fprime`. You should see the failure output.

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Fixes #1366

### CODE REVIEW

**Comment by LeStarch** [comment]
@bocchino would you review?  The issue was this:  

1. The test occasionally sends corrupted frames to prove the Deframer works on corrupt input
2. A corrupt frame may need to be flushed through the system
3. When frames are flushed through the system there is no "expected answer" data to compare against, and thus failure ensues.

The fix: mark when we are flushing frames through and ignore them rather than compare them to non-existent expected data.

**Comment by bocchino** [comment]
Looks good, and passes on the seed that failed before. But now I'm getting this failure on seed 732440:
```
[I] bocchino@MT-306179 ~/J/T/F/L/f/b/b/Darwin (fix/deframer-ut) [1]> cat seed-history 
545994
545994
732440
[I] bocchino@MT-306179 ~/J/T/F/L/f/b/b/Darwin (fix/deframer-ut)> tail -n 1 seed-history > seed
[I] bocchino@MT-306179 ~/J/T/F/L/f/b/b/Darwin (fix/deframer-ut)> ./Svc_Deframer_with_fprime
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from Nominal
[ RUN      ] Nominal.RandomizedDeframer
Ran 10000 steps.
[       OK ] Nominal.RandomizedDeframer (918 ms)
[ RUN      ] Nominal.RandomizedPollingDeframer
/Users/bocchino/JPL/Tools/FPrime/LeStarch/fprime/Svc/Deframer/test/ut-unified/Tester.cpp:56: Failure
Expected: (m_receiving.size()) > (0), actual: 0 vs 0
Check-data receiving queue empty after filtering down 1 elements

Ran 10000 steps.
[  FAILED  ] Nominal.RandomizedPollingDeframer (942 ms)
[ RUN      ] Nominal.BasicUplink
[       OK ] Nominal.BasicUplink (2 ms)
[ RUN      ] Nominal.BasicPollUplink
[       OK ] Nominal.BasicPollUplink (1 ms)
[----------] 4 tests from Nominal (1864 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (1864 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Nominal.RandomizedPollingDeframer

 1 FAILED TEST
```

**Comment by LeStarch** [comment]
@bocchino  this should be fixed. I ran ~60 random seeds and have not seen another failure.

**Review by bocchino — APPROVED** [review]
Looks good!

**Pull request merged**
