### PR TITLE
Added information on STest

### PR DESCRIPTION
**Pull request by Anirban166**
| | |
|:---|:---|
|**_Originating Project/Creator_**| @Anirban166 |
|**_Affected Component_**| STest |
|**_Affected Architectures(s)_**| -/- |
|**_Related Issue(s)_**| -/- |
|**_Has Unit Tests (y/n)_**| -/- |
|**_Builds Without Errors (y/n)_**| y |
|**_Unit Tests Pass (y/n)_**| y |
|**_Documentation Included (y/n)_**| y |

---
## Change Description

Added a bit of information on STest (based on my understanding) since documentation didn't make it in during the initial import.

## Rationale

Might help someone trying to understand/use/extend the testing framework!

### CODE REVIEW

**Comment by ThibFrgsGmz** [comment]
Awesome, I've been wondering about this for a long time!

**Comment by LeStarch** [comment]
@bocchino would you review this?  It involves our basic STest setup.

**Review by bocchino — APPROVED** [review]
@Anirban166 Looks good, thanks for this contribution! I made a few changes for style and content.

**Comment by LeStarch** [comment]
Not sure why the spell checker is angry, but nothing flagged within.

**Pull request merged**
