### PR TITLE
Remove old binary UT files

### PR DESCRIPTION
**Pull request by saba-ja**
| | |
|:---|:---|
|**_Originating Project/Creator_**| F Prime |
|**_Affected Component_**|  All |
|**_Affected Architectures(s)_**| - |
|**_Related Issue(s)_**| #689 |
|**_Has Unit Tests (y/n)_**|  Y |
|**_Builds Without Errors (y/n)_**|  Y |
|**_Unit Tests Pass (y/n)_**| Y |
|**_Documentation Included (y/n)_**| N |

---
## Change Description

This PR removes all the old binary executable unit test files from the UT folders.
The deleted files are one of the following:

- runtest_CYGWIN
- runtest_DARWIN
- runtest_LINUX
- runtest_all 

No other file was deleted in this PR.

## Rationale

With the new fprime-util tool there is no need to keep the old executable files.

## Testing/Review Recommendations

Ran `fprime-util check --all` with no issue.

## Future Work

Cleaning up the GoogleTest and gcov files will be done in separate PRs.

### CODE REVIEW

**Comment by saba-ja** [comment]
@LeStarch, the spell check error is due to `czf` and `gz` in the following file:
https://github.com/nasa/fprime/blob/045934db49761870242742134ec026e3cfb31162/ci/helpers.bash#L19
I did not add these to the exception list to not cause merge conflict with previous PRs.
These were introduced a PR in the past and seems they are carrying on to new PRs.

**Comment by jsoref** [comment]
Actually, it looks like it was introduced in a commit that was sent to `devel` w/o a PR (8 hours ago afaict), but yes, there's already a PR with a fix for it, so avoiding merge conflicts is a good idea.

**Comment by LeStarch** [comment]
Yes, an unanticipated test of our branch protection rules.....that oversight is fixed now!  And I did a PR to fix the spelling issue.

**Comment by LeStarch** [comment]
Once that PR is merged the spelling issue will go away, and our builds will pass again.

**Comment by LeStarch** [comment]
Ok, we merged in the fix.  I got an approval review from @Joshua-Anderson from the non-PRed submitted commit too so apart from being 2 entries in the git log we have had eyes on the changes.

The branch rules are fixed to prevent this in the future and I rerand the failed spelling workflows here.

**Review by LeStarch — APPROVED** [review]

**Pull request merged**
