### PR TITLE
docs: Update MathComponent to Reference TestMain

### PR DESCRIPTION
**Pull request by astroesteban**
| | |
|:---|:---|
|**_Originating Project/Creator_**|@astroesteban |
|**_Affected Component_**| Docs |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

The existing MathComponent unit test tutorial instructs the user to create a main.cpp test file even though running `fprime-util impl --ut` creates a new TestMain.cpp file. The changes update the Tutorial.md file to reflect this new functionality and now instruct the user to modify the autogenerated TutorialMain.cpp file instead of creating a main.cpp file.

In addition, the existing main.cpp files for the MathSender & MathReceiver components have been renamed to TestMain.cpp.

## Rationale

Update the docs to reflect more features provided by `fprime-util impl --ut`

## Testing/Review Recommendations

- Review the renaming of `main` to `TestMain`.

## Future Work

### CODE REVIEW

**Comment by LeStarch** [comment]
@astroesteban thanks!  I added a few more fixes w.r.t. TesterBase and GTestBase files being autocoded.

**Review by LeStarch — APPROVED** [review]
Looks Good!

**Comment by astroesteban** [comment]
Thanks for those extra fixes @LeStarch!

**Comment by LeStarch** [comment]
@astroesteban you did the work, I was just cleaning up an old issue.

**Pull request merged**
