### PR TITLE
Switch to Github Actions Code Scanner

### PR DESCRIPTION
**Pull request by thomas-bc**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**| Github Actions |
|**_Related Issue(s)_**| https://github.com/nasa/fprime/issues/1693 |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**| |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Adds a Github Actions workflow that runs the same queries as the current LGTM set up.

## Rationale

[lgtm.com](lgtm.com) will be shut down at the end of the year.

## Future Work

We may want to remove the LGTM configuration files once it's fully shut down.

## Additional comments
I currently have it set up to run on each commit and pull request to `master` and `devel` as I see this seems to be the convention in the workflows of this repo, but we could restrict to only running when source files are modified.

Here's the result of the queries [on Github Actions results](https://github.com/thomas-bc/fprime/security/code-scanning?query=is%3Aopen+branch%3Agh-code-scanner). Comparing to [the LGTM results](https://lgtm.com/projects/g/nasa/fprime/alerts/?mode=tree), we see the same warnings with an additional 2 on the Github Actions side.

### CODE REVIEW

**Review by LeStarch — CHANGES_REQUESTED** [review]
Looks good to me.  We should fix the one error, so that doesn't count against us.  Then we'll merge.

**Comment by thomas-bc** [comment]
I added in the fix for the Python error. Turns out the if statement isn't needed at all, the behavior would be the same for any list length >0. There is no check to ensure that the list isn't empty though, but I didn't want to risk to break things in the scope of this PR so I didn't add that. It also looks like these functions aren't used anyways.

**Review by LeStarch — APPROVED** [review]
Approved!

**Comment by LeStarch** [comment]
This fix looks right to me.  Also `.split` should never return an empty list as it would always return back a list of at least one element.

**Pull request merged**
