### PR TITLE
FP-2784: define trace id type

### PR DESCRIPTION
**Pull request by Shivaly-Reddy**
| | |
|:---|:---|
|**_Related Issue(s)_**| 2784 |
|**_Has Unit Tests (y/n)_**| N  |
|**_Documentation Included (y/n)_**| N |

---
## Change Description

Adding a trace id type for FPP.

## Rationale

There is a corresponding change being PRed for fpp/main - https://github.com/nasa/fpp/pull/517

## Testing/Review Recommendations

Been used and tested with FP-2784 (implementation of Trace features)

## Future Work

Trace feature will be added.

### CODE REVIEW

**Review by bocchino — APPROVED** [review]
Looks good to me!

**Comment by Shivaly-Reddy** [comment]
@LeStarch : I don't think I have the permission to merge the approved pull request? This change needs to be merged in-sync with the corresponding fpp change. Can you please let me know what's the best way to do that?

**Comment by thomas-bc** [comment]
@Shivaly-Reddy  The usual process for this it to merge https://github.com/nasa/fpp/pull/517, pre-release FPP and upgrade the pre-release version in requirements.txt here in this PR

**Comment by Shivaly-Reddy** [comment]
Thanks @thomas-bc, Rob gave me the alpha version that would contain the expected changes. Once its released, I'll go ahead and update the requirements.txt.

**Comment by bocchino** [comment]
FPP v2.2.0a5 is now available.

**Review by LeStarch — APPROVED** [review]

**Pull request merged**
