### PR TITLE
Upgrade Python Packages (requirements.txt)

### PR DESCRIPTION
**Pull request by thomas-bc**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**| requirements.txt |
|**_Related Issue(s)_**| https://github.com/nasa/fprime/issues/1690 |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Update `requirements.txt` - bump up package versions, as some have been flagged insecure.

## Rationale

https://github.com/nasa/fprime/issues/1690

## Testing/Review Recommendations

CI checks

### CODE REVIEW

**Comment by thomas-bc** [comment]
@LeStarch wow! Looks like there's no complaints. Can you think of any further (manual?) steps to validate that we're good to ship those updates?

**Comment by ThibFrgsGmz** [comment]
fprime-fpp has decreased in minor version number, is this intended? 🤔

**Comment by thomas-bc** [comment]
Ah it was not intended, thank you for catching that!

**Comment by LeStarch** [comment]
@thomas-bc, yes, you should run the fprime-gds and verify functions in the HTML GUI.  Given that Flask and friends has upgraded and the CI bypasses the HTML GUI we should verify those functions by hand.

**Review by LeStarch — APPROVED** [review]
This does fix all 4 security items!

**Pull request merged**
