### PR TITLE
lestarch: adding gds.ini per suggestion by @rdaruwala

### PR DESCRIPTION
**Pull request by LeStarch**
Adding missing gds.ini

### CODE REVIEW

**Comment by LeStarch** [comment]
@rdaruwala can you take a look at this fix?

**Comment by timcanham** [comment]
No idea what this does...

**Comment by LeStarch** [comment]
@timcanham this adds the gds.ini file to RPI directory.  Unless specifically pointed to, the gds.ini is expected in the deployment directory, and thus RPI needs one to work with the Gds.

**Comment by LeStarch** [comment]
I should clarify, it adds a default gds.ini.

**Pull request merged**
