### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by thomas-bc**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Downgrading `importlib-metadata` to `5.2.0` because 6.0 was causing issues to Python 3.7.

## Testing/Review Recommendations

Should pass the check introduced by https://github.com/nasa/fprime/pull/1905 once that one is merged in.

### CODE REVIEW

**Review by LeStarch — APPROVED** [review]
Looks like it will fix the issue! I merged the other PR, so I am hoping this change will run that new check.

**Comment by LeStarch** [comment]
Closing and reopening seems to have the best chance of properly updating items.

**Comment by LeStarch** [comment]
@thomas-bc still having issues here.  Looks like we are forced to downgrade below 5.0 until we can discontinue 3.7

**Comment by thomas-bc** [comment]
I bumped it back down to the latest 4.X, which worked locally with Python37

**Pull request merged**
