### PR TITLE
Improvements to Circular Buffer

### PR DESCRIPTION
**Pull request by bocchino**
|Change|Rationale|
|----|----|
|Revise implementation to use a head index and an allocated size instead of head and tail pointers|Simplifies the implementation. Eliminates the one-byte discrepancy between the physical and logical store sizes.|
|Replace `get_remaining_size(bool)` with `get_allocated_size` and `get_free_size`|The interface is easier to understand.|
|Add `const` to interface functions where possible|C++ coding practice
|Add SDD|Required documentation

### CODE REVIEW

**Comment by bocchino** [comment]
@LeStarch CI is failing because of setup dependencies. Can you investigate?

**Comment by LeStarch** [comment]
@bocchino I have to fix CI first.  Could you review: https://github.com/nasa/fprime/pull/1314?  It should fix the problem

**Comment by bocchino** [comment]
I reviewed and approved #1314.

**Review by LeStarch — APPROVED** [review]

**Comment by LeStarch** [comment]
Just looked through this and it looks like what I'd expect!  CI passes, so I am going to merge it.

**Pull request merged**
