### PR TITLE
trouble-shooting-guide-2500

### PR DESCRIPTION
**Pull request by rlcheng**
- Add troubleshooting.md. This is currently a copy of the troubleshooting section of https://nasa.github.io/fprime/INSTALL.html

| | |
|:---|:---|
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

A description of the changes contained in the PR.

## Rationale

A rationale for this change. e.g. fixes bug, or most projects need XYZ feature.

## Testing/Review Recommendations

Fill in testing procedures, specific items to focus on for review, or other info to help the team verify these changes are flight-quality.

## Future Work

Note any additional work that will be done relating to this issue.

### CODE REVIEW

**Comment by LeStarch** [comment]
@rlcheng the one change I would ask for is to delete the "Troubleshooting" section from INSTALL and link to this one instead!

Something like: `For users having issues, please consult our [trouble shooting guide](./troubleshooting.md).` or whatever sounds best to you!

**Review by LeStarch — CHANGES_REQUESTED** [review]
Request that you delete the copied section and link, other than that this is *awesome*!

**Comment by rlcheng** [comment]
> Request that you delete the copied section and link, other than that this is _awesome_!

Updates made. Old troubleshooting guide removed and link added. Tested and working.

**Review by thomas-bc — APPROVED** [review]
🚀

**Review by LeStarch — APPROVED** [review]

**Pull request merged**
