### PR TITLE
added missing cpp file for baremetal

### PR DESCRIPTION
**Pull request by kevin-f-ortega**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Updated CMakeList file to include the IntervalTimer.cpp for bare metal.

## Rationale

This cpp file is needed when building for bare metal.

## Testing/Review Recommendations

Fill in testing procedures, specific items to focus on for review, or other info to help the team verify these changes are flight-quality.

## Future Work

Note any additional work that will be done relating to this issue.

### CODE REVIEW

**Review by arizvi786 — APPROVED** [review]
LGTM

**Comment by LeStarch** [comment]
I count 7 baremetal stub files, and 4 listed for compilation.  Should we not be adding more?

**Review by LeStarch — APPROVED** [review]
This change seems correct, but I wonder if we need to add more of the missing stubs?

**Comment by kevin-f-ortega** [comment]
> This change seems correct, but I wonder if we need to add more of the missing stubs?

Let me double check.

**Comment by kevin-f-ortega** [comment]
@LeStarch updated cmake list file.

**Review by LeStarch — APPROVED** [review]
@kevin-f-ortega this is now "right" or at least better that it was. However, there is a deeper problem here that another project discovered:

What if a user wants to use "BAREMETAL" for threads, but posix files?  Nothing specifically prevents this except for the structuring of this cmake file.  Same with queues etc.

As we expand the use of `BAREMETAL` we really ought to consider what it means.

As we look to alternative OS implementations, we really out to make structuring them easier.

Still, these problems are only loosely affiliated, so this PR should be `approved`

**Comment by LeStarch** [comment]
@kevin-f-ortega squash and merge, you have the honors.

**Pull request merged**
