### PR TITLE
Add the "Open in VS Code" badge to improve UX 

### PR DESCRIPTION
**Pull request by ThibFrgsGmz**
| | |
|:---|:---|
|**_Originating Project/Creator_**| @ThibFrgsGmz  |
|**_Affected Component_**|  Development environment / UX |
|**_Affected Architectures(s)_**| N/A |
|**_Related Issue(s)_**| N/A |
|**_Has Unit Tests (y/n)_**| N/A |
|**_Builds Without Errors (y/n)_**|  N/A |
|**_Unit Tests Pass (y/n)_**| N/A |
|**_Documentation Included (y/n)_**| n |

---
## Change Description

This PR simply integrates the "Open in VS Code" badge into the README.md to further enhance the user experience with fprime.

[Open in Visual Studio Code](https://open.vscode.dev/nasa/fprime)

## Rationale

The June 2021 release of Visual Studio Code includes the addition of the "Open in VS Code" badge (https://code.visualstudio.com/updates/v1_58) to allow visitors to quickly open a GitHub repo in the VS Code open source editor.

With this badge, visitors can either use the recently launched VS Code Remote Repositories extension or clone into a Dev Container.

By clicking on the badge, visitors will be directed to a page on https://open.vscode.dev/nasa/fprime, where they can choose how to continue in VS Code. An example is available on the VS Code GitHub repo: https://github.com/microsoft/vscode.

## Testing/Review Recommendations

Visitors will need to install the "Remote Repositories" extension of their Visual Studio Code (https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub) which allows working with GitHub source code repositories quickly and safely in VS Code.

## Future Work

None

### CODE REVIEW

**Review by ugo94490 — APPROVED** [review]

**Comment by LeStarch** [comment]
For now, we feel this should be either kept in a repository under https://github.com/fprime-community or under a fork of F´.  Should it turn out that the vast majority of our users need this feature, we'd consider it in the core repo.  The reason for this is it will add a maintenance, support, and advice overhead for a technology we are less familiar with.

**Comment by ThibFrgsGmz** [comment]
You're right, I should have opened a discussion in the project's GitHub before taking action on this enhancement.

I found this feature interesting for developers like me who program almost exclusively on VS Code.

**Comment by LeStarch** [comment]
@ThibFrgsGmz, to be clear we do appreciate the contribution.  fprime-community is a great place for things in this nature.

"fprime" itself is intended to be engineered to "flight standards", which means our core team must maintain all contributions here and support users with using those contributions.  Given my inexperience with VsCode I am hesitant to support users who see it on our README.

To help me build experience, have you successfully built and debugged F´ within VsCode?  I tried it out and I could not get our CMake setup to mesh well with VsCode.  I'd be very interested in hearing your experience in VsCode because I know many devs who use it with F´....but not yet has used it to any degree past code-highlighting.

**Comment by ThibFrgsGmz** [comment]
@LeStarch Sorry for the delay, I'm doing a lot of things at the same time and I don't know where to put my head.

Here is how I develop on F Prime with VS Code.

I launch Visual Studio Code from WSL-2 in my project directory.
I think it's since the addition of the "Remote Repositories" feature something like that that this is possible.
It allows me to have a kind of remote dev environment since WSL-2 is a container.
So I guess it should be possible if you run F Prime in a local Docker container based on Ubuntu 20.04.

Then with the terminal available from Visual Studio Code I am able to launch all the installation commands of F Prime, compile my binary and launch the GDS.
There is no problem on my side, you tell me that it did not work on your side?

For debugging, since my mockups are quite simple I didn't need to really use the debugger.

Nevertheless I tried at the beginning of the week by adding the specification CMAKE_BUILD_TYPE=Debug in one of the high level CMakeFile but the debugging symbols don't seem to have been generated since VS Code doesn't find a source file when I launch the debugger.

I just looked tonight if it was me who didn't know how to configure in debug or if it was a bug. And if it's a bug, if it was reported.
To my great surprise there is an issue opened recently: https://github.com/nasa/fprime/issues/838.

Once this issue is solved I should be able to debug on Visual Stdio Code. I could give you a little tutorial if you want, and eventually put it on the F Prime website (I thought I saw a VS Code section somewhere back then).

I'd be curious to know what IDEs you use and how do you debug F Prime step by step

PS: I don't know if I'll have time to fix the bug before someone else fixes it. Especially since I finally understand where the sources of the fprime-tools and fprime-gds utilities are located.
Last Sunday night I was looking everywhere in fprime/autocoders/python without finding anything.  I have difficulty to see what really contains fprime/autocoders/python if finally the autocoder fprime-util is not there, I had to get lost in the code at first sight.

**Comment by Joshua-Anderson** [comment]
> There is no problem on my side, you tell me that it did not work on your side?

I think @LeStarch was not that it didn't work, but the maintenance cost of promising first class VsCode support for F', since proper F' cmake integration with an IDE can be tricky.

> I'd be curious to know what IDEs you use and how do you debug F Prime step by step

I use Visual Studio code as well, but I keep it simple and haven't integrated cmake. VsCode usually manages to pick up the autogenerated code but a lot of `#define`s aren't set correctly so I still usually get editor warnings. Several contributors use CLion and have integrated in its cmake support with F'.

I usually use fprime-util to build and then launch the binary with gdb to debug.

> Last Sunday night I was looking everywhere in fprime/autocoders/python without finding anything. I have difficulty to see what really contains fprime/autocoders/python if finally the autocoder fprime-util is not there, I had to get lost in the code at first sight.

Yeah, fprime-util and the gds were recently relocated out of core F' so that they could could be versioned separately. We should probably add a note to the docs about their repository location.

**Comment by ThibFrgsGmz** [comment]
I see VSCode more as a powerful text editor than as an IDE in the sense that it does not provide a compiler for an embedded platform, or that it gives us direct access to the terminal rather than opening a terminal in a new window.

As for my question, I thought I understood that he had failed to build and debug F Prime with VSCode, hence his question:

> "To help me gain experience, have you successfully built and debugged F' in VsCode? I've tried and I haven't been able to get our CMake setup to integrate well with VsCode."

My bad in this case!


I'm not thinking of integrating CMake in my Visual Studio at least in the use case you might be thinking of. It seems to me that I only have the CMake extension to have the synthesized coloring when editing CMake file, maybe I'm wrong

Then I use the CMake of my WSL-2 to launch the buildchain of FPrime through the terminal of WSL-2, however instead of opening another window for the terminal I use the one directly provided in VSCode.

> "I usually use fprime-util to build and then launch the binary with gdb to debug."

Directly in the VSCode terminal?
I thought that in the problem I quoted above, there were no debugging symbols when we ask to build in debug mode, making gdb useless.

**Comment by Joshua-Anderson** [comment]
> I'm not thinking of integrating CMake in my Visual Studio at least in the use case you might be thinking of. It seems to me that I only have the CMake extension to have the synthesized coloring when editing CMake file, maybe I'm wrong

Agreed, I do the same... slightly better autocomplete would be nice but I also mostly use VsCode as a glorified text editor so I haven't messed around with properly configuring cmake either beyond just installing the plugin

> I thought that in the problem I quoted above, there were no debugging symbols when we ask to build in debug mode, making gdb useless.

Oh yeah I forgot about that! I just drop `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g")` in my cmake project file.
Right now fprime-util has first class support for the Release and Test environments but not Debug yet. One thing I've had on the fprime-util backburner is actually adding first class support for the debug build type so you could do things like `fprime-util generate --debug` and `fprime-util build --debug`.

**Pull request closed without merging**
