### PR TITLE
Replace 32 with total cpu thread(s)

### PR DESCRIPTION
**Pull request by Uniminin**
`"$(nproc || printf '%s\n' 1)"` will return total number of cpu thread(s) if it returns `0` else `1`.

### CODE REVIEW

**Review by Uniminin — COMMENTED** [review]
All fine!

**Comment by LeStarch** [comment]
What do you think of setting it to a small number, say `4` instead?  Since this is the Install guide we want it very clear what this code does.

Alternatively, we could pull this into a note on how to build with all machine cores.

Thoughts?

**Review by LeStarch — COMMENTED** [review]
What do you think of setting it to a small number, say 4 instead? Since this is the Install guide we want it very clear what this code does.

Alternatively, we could pull this into a note on how to build with all machine cores.

Thoughts?

**Comment by Uniminin** [comment]
> What do you think of setting it to a small number, say 4 instead? Since this is the Install guide we want it very clear what this code does.
> 
> Alternatively, we could pull this into a note on how to build with all machine cores.
> 
> Thoughts?

Setting it 4 isn't a good idea. What if anyone is building on a single or dual core processor. 4 jobs won't really help or may make it worse.

If not best but better way will be if it detects the total number of cpu threads on a system and apply the jobs according to it. Which is what i did on my commit on this PR.

**Comment by Uniminin** [comment]
My commit is simple. `nproc` returns total number of cpu threads (check `man nproc`.
Brief Explanation: https://github.com/nasa/fprime/pull/258#issue-521143662

**Comment by Uniminin** [comment]
> Alternatively, we could pull this into a note on how to build with all machine cores.
Not necessary. people can understand. we could add a small note if we want but again that's not very necessary.

**Review by LeStarch — APPROVED** [review]

**Comment by LeStarch** [comment]
Decided I like this fix.  It is better then recommending 32 processes for even small machines.  Thanks!!!

**Pull request merged**
