### PR TITLE
Update CI to use Json dictionaries

### PR DESCRIPTION
**Pull request by Lex-ari**
| | |
|:---|:---|
|**_Related Issue(s)_**| [nasa/fprime-gds#177](https://github.com/nasa/fprime-gds/pull/177) |
|**_Has Unit Tests (y/n)_**| y |
|**_Documentation Included (y/n)_**| y |

---
## Change Description

Updates CI to use Json dictionaries instead of XML dictionaries.

This essentially replaces `TopologyAppDictionary.xml` to `TopologyDictionary.json` in the RPi Test and fputil ci test.
This also updates guides to use Json dictionaries.

## Rationale

Updates since fprime-seqgen should use json dictionaries instead of xml for future versions of fprime.

## Testing Recommendations

Ensure CI is still functional and correct and perhaps do additional testing on hardware.

cc @Joshua-Anderson @kevin-f-ortega

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
Looks good! I don't think this will pass yet, since we haven't done a release of the GDS with json dict support yet. @thomas-bc does it possibly make sense to do a alpha release of the GDS so that the core fprime repository can swap over and start testing against JSON dictionaries?

**Comment by LeStarch** [comment]
@Joshua-Anderson yes, it does!

**Review by LeStarch — APPROVED** [review]

**Comment by LeStarch** [comment]
@Lex-ari I did the alpha releases, committed the bump to your branch, de-conflicted another conflict, and CI is rerunning.  Hopefully, this will resolve the issue.

**Comment by Lex-ari** [comment]
I think this also needs to be changed... https://github.com/nasa/fprime/blob/129d7f54e22f1fe4cc09d0af6effff79b00f08f0/.github/workflows/build-test-rpi.yml#L20

Looking at the log, something is still expecting an XML header. I'm going to find it.

**Comment by Lex-ari** [comment]
Could it be that CI is still using the old version of fprime-gds?
https://github.com/nasa/fprime/actions/runs/10086104803/job/27888181461?pr=2806#step:3:16
https://github.com/nasa/fprime/actions/runs/10086104818/job/27888308920?pr=2806#step:2:11
https://github.com/nasa/fprime/actions/runs/10086104818/job/27888308920?pr=2806#step:4:17

**Review by thomas-bc — COMMENTED** [review]
Yes, we haven't done a release and that's what's causing issues here. We have done an Alpha release but not a full one - the pip install doesn't catch the alpha release because the workflow has code `pip install fprime-gds` and not to install from requirements.txt

**Comment by LeStarch** [comment]
Fixed requirements.  Will update CI GDS version.

**Comment by LeStarch** [comment]
Note: breakages are blocking on tutorial PRs.  Well get those merged tomorrow and rerun.

**Comment by thomas-bc** [comment]
@LeStarch I had to make a change to install `requirements.txt` in the RPI workflows. Turns out it was using a version that's installed on the RPI hosts. Used to work fine, but broke here since we are switching to JSON dictionary and therefore need a newer release.

**Review by jwest115 — APPROVED** [review]

**Pull request merged**
