### PR TITLE
Update fprime cli documentation

### PR DESCRIPTION
**Pull request by SMorettini**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**| Documentation |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Update the documentation of the fprime-cli.

### CODE REVIEW

**Comment by SMorettini** [comment]
The spell-checking is failing for `non-existent`, should I add it in the exceptions or changed in the documentation? It comes from running `fprime-cli --help`

**Review by thomas-bc — COMMENTED** [review]
If that's outputted by fprime-cli it's probably best to add it to the expected list. Thanks for updating this!

**Comment by thomas-bc** [comment]
**Food for thought:**
this pattern of displaying in the docs what the output of a `--help` command outputs seems questionable to me. For example, the next release of `fprime-gds` will yet again modify this output, replacing `-r` with `-d` (see [here](https://github.com/fprime-community/fprime-gds/commit/f700190125d578d3f082beb399936a5b3a68ddab#diff-20f9d3d050b68198cff1c8cc88f0baa2cfd8f9ef1f3ba661d076134625ef1927R207)). Are we going to have to remember to update this again then? Most likely, we will forget. Should these things be scrubbed? Could we auto-generate them somehow?

**Comment by SMorettini** [comment]
I updated the exception to solve the spelling issue. About 

> **Food for thought:** this pattern of displaying in the docs what the output of a `--help` command is seems questionable to me. For example, the next release of `fprime-gds` will yet again modify this output, replacing `-r` with `-d` (see [here](https://github.com/fprime-community/fprime-gds/commit/f700190125d578d3f082beb399936a5b3a68ddab#diff-20f9d3d050b68198cff1c8cc88f0baa2cfd8f9ef1f3ba661d076134625ef1927R207)). Are we going to have to remember to update this again then? Most likely, we will forget. Should these things be scrubbed? Could we auto-generate them somehow?

I agree, I think that if we can autogenerate it would be very interesting but I'm not an expert in CI setup so I don't know how to do it. I think it can also make sense to remove it from the documentation since the user can find it by itself. If you want me to remove it I can do it directly in this pull request. Let me know what you prefer.

**Comment by LeStarch** [comment]
There is reason to keep this around, but I'd argue in a different format. Like how online Linux man-pages are setup.  Autogeneration would be awesome, and it should be relegated to API like documentation rather than inside the user guide.

This is a nice stop-gap, so I'll merge.

**Pull request merged**
