### PR TITLE
Handle 0 and negative numbers on string_copy

### PR DESCRIPTION
**Pull request by Drosaca**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Avoids  to write '\0' before  the destination pointer if num is 0
which is set by the following line:
> destination[ num - 1] = '\0'

### CODE REVIEW

**Comment by ThibFrgsGmz** [comment]
The verification of the negative number seems useless because the number passed in parameter is not signed. Right ?

**Comment by Drosaca** [comment]
@ThibFrgsGmz Indeed the check of negative values has been removed, nevertheless when num equals zero '\0' will still be written at destination[-1]

**Review by LeStarch — APPROVED** [review]

**Comment by LeStarch** [comment]
I agree with this improvement.  In the case where 0 is supplied as a limiting length, then the destination should return unchanged as the limit does not even account for a terminating `\0`.  This will will remove the error.

**Comment by LeStarch** [comment]
Closed and reopened as I needed to try and re-trigger a complete rerun of CI to fix the python formatting bug.  If it doesn't work, we'll ignore that check as the python was not touched.

**Pull request merged**
