### PR TITLE
add responsive layouts

### PR DESCRIPTION
**Pull request by adityadees**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

CSS update for better responsive display on mobile devices
add overflow for .toctree-wrapper.compound and new class .table-responsive
Before :

After :

## Rationale

A rationale for this change. e.g. fixes bug, or most projects need XYZ feature.

## Testing/Review Recommendations

Fill in testing procedures, specific items to focus on for review, or other info to help the team verify these changes are flight-quality.

## Future Work

Note any additional work that will be done relating to this issue.

### CODE REVIEW

**Review by maulikdadhaniya — CHANGES_REQUESTED** [review]
add more specific class name

**Comment by adityadees** [comment]
> add more specific class name

this just a little changes.
i'm just use an existing class name and add it into css.  
toctree-wrapper compound
ex : fprime\docs\UsersGuide\api\python\fprime-gds\html




and for 'table-responsive' such as familiar bootstrap class name

**Comment by LeStarch** [comment]
We generate these HTML files automatically using the sphinx tool for python.  Thus these changes will be overwritten in our next release.   We should instead take the action to move this setup into the sphinx configuration.

**Comment by LeStarch** [comment]
Tracked in #499

**Pull request closed without merging**
