### PR TITLE
Fixing minor issues - second version(devel to devel)

### PR DESCRIPTION
**Pull request by EverLookNeverSee**
Applying final requested changes by reviewer.

### CODE REVIEW

**Comment by LeStarch** [comment]
I am going to let this run through CI.

**Comment by EverLookNeverSee** [comment]
@LeStarch CI/build failed, what should we do now?

**Comment by LeStarch** [comment]
@EverLookNeverSee  I see a number of regressions from the latest devel.  Do you mind If I fix these and push to your branch?

**Comment by EverLookNeverSee** [comment]
> @EverLookNeverSee I see a number of regressions from the latest devel. Do you mind If I fix these and push to your branch?

No problem, Feel free to do any changes that makes this PR ready to merge.

**Comment by LeStarch** [comment]
@EverLookNeverSee I forced pushed to your devel with changes that should help this build.  I also fixed up several things:

1. Rebased to nasa/devel
2. Reverted some changes.  These tended to be higher risk and should be made their own PR.
3. Restored new commits from nasa/devel
4. Cleaned up many of your TODOs since you asked for maintainer support

**Comment by LeStarch** [comment]
You should pull form your own fork's devel before making other changes....and let's get this PR merged as-is first.

Thanks for all the hard work!

**Review by EverLookNeverSee — COMMENTED** [review]
LGTM!

**Comment by EverLookNeverSee** [comment]
@LeStarch Checks are passed successfully

**Review by saba-ja — APPROVED** [review]
Went over the changes one more time. Built Ref and ran the GDS with no apparent issue. 
This PR should be fine to be merged into devel.

**Review by LeStarch — APPROVED** [review]

**Comment by EverLookNeverSee** [comment]
Thank you @LeStarch @saba-ja

**Pull request merged**
