### PR TITLE
Fix/pr 769

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

A description of the changes contained in the PR.

## Rationale

A rationale for this change. e.g. fixes bug, or most projects need XYZ feature.

## Testing/Review Recommendations

Fill in testing procedures, specific items to focus on for review, or other info to help the team verify these changes are flight-quality.

## Future Work

Note any additional work that will be done relating to this issue.

### CODE REVIEW

**Review by LeStarch — COMMENTED** [review]
LGTM

**Comment by LeStarch** [comment]
@bocchino you'll need to review this to make sure my "fix" didn't change anything.  Your changes look ok.

Once you approve:
1. We should merge  this.  I prefer a "squash"
2. You **must** start with a clean branch off release/v3.0.0 after this fix.  History is pretty warped, but this will fix it.

**Comment by LeStarch** [comment]
@bocchino it also looks like the RPI deployment doesn't build as it wasn't updated for the changes.  I won't fix this, but we should soon as CI checks for it.

**Review by bocchino — APPROVED** [review]
Looks great! Thanks, Michael. Let's merge this and then I'll make a separate PR to fix the RPI build.

**Comment by LeStarch** [comment]
Merging.

**Pull request merged**
